### ISSUE TITLE
Problem With reading Capacitance

### ISSUE THREAD

**Issue by LaVoute974** [adrien3d/IO_AD7150#2]
Hello ! 

First thank you for your library !

When I try to upload the demo code, it only gave me 4095 when  I connect any capacitance ! Is it normal ? 

Thank you in advance for your answer !

**Comment by adrien3d** [comment]
Hi @LaVoute974,

This is not normal, this library was tested when published, did you double check your connections ?

**Comment by LaVoute974** [comment]
Yes, double checked ! I search other example code with no success...

**Comment by adrien3d** [comment]
Try those ones:
https://forum.arduino.cc/index.php?topic=438443.0
http://blog.nearfuturelaboratory.com/2007/01/11/arduino-and-twi/

**Comment by adrien3d** [comment]
@LaVoute974 any progress?
